### ISSUE TITLE
Gitbook에 연동해주실 수 있으신가요?

### ISSUE THREAD

**Issue by benjioh5** [SHOM95/2016ICEWALL_AndroidStudy#1]
Github 레포지토리를 Gitbook에 연동하면, 책 형태로 문서를 읽을 수 있습니다. [제 레포지토리](https://github.com/benjioh5/icewall-guideline) 와 [제 gitbook](https://www.gitbook.com/book/deadbeef/icewall-guideline/details) 을 참고해서, 사용하다고 생각되면 연결한 뒤 문서 작성 부탁드립니다.

**Comment by benjioh5** [comment]
확인을 하셨으면 이슈를 닫던지, 코멘트를 달아주시던지 해주시죠 ㅠㅠ

**Comment by SHOM95** [comment]
아 확인했어요 ㅋㅋㅋㅋㅋ

**Comment by yosangwon** [comment]
굳이 GitBook 형태로 사용할 필요가 있나요? 그냥 정적 페이지 생성기로도 할 수 있을 것 같은데 굳이..

**Comment by benjioh5** [comment]
지킬을 쓰면, 여러 개의 스터디 관리가 애매해지지 않을까 싶어서 그런 부분도 있어요. -_-a 일단, 지금은 gitbook으로 테스트해보고, 오버헤드나 트레이드오프가 너무 크다 싶으면, 정적 페이지 생성기 쪽으로 넘어갈꼐요.
